config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  
  resources :sections do
  	resources :questions
  end

  resources :submissios do
  	resources :questions
  end	

  resources :submissios do
  	resources :answers
  end



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :submissio
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :section#, dependent: :destroy_async
  has_many :answers, dependent: :destroy
  accepts_nested_attributes_for :answers
end

app/models/section.rb
class Section < ApplicationRecord
	has_many :questions, dependent: :destroy
	accepts_nested_attributes_for :questions
end

app/models/submissio.rb
class Submissio < ApplicationRecord
  belongs_to :user
  has_many :answers, dependent: :nullify
  has_many :questions, through: :answers
  has_many :sections, through: :questions
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :submissios
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def index
    @submissio = Submissio.find(params[:submissio_id])
  end

  def show
    @submissio = submissio.find(params[:submissio_id])
  end

  def edit
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
	def index
		@sections = Section.all
		@questions = Question.all
		@submissio = Submissio.find(params[:submissio_id])
	end

	def show
		@question = Question.find(params[:id])
	end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
	before_action :set_section, only: [:show, :edit, :update, :destroy]

	def index
		@sections = Section.all
	end


	private

	def set_section
		@section = Section.find(params[:id])		
	end

	def section_params
		params.require(:section).permit(:name)
	end
end

app/controllers/submissios_controller.rb
class SubmissiosController < ApplicationController
	before_action :set_submissio, only: %i[ show edit update destroy ]

	def index
		@submissios = Submissio.all
	end

	def new
		@submissio = Submissio.new
	end

	def show
	end

	def create
		@submissio = Submissio.new(submissio_params)
		@submissio.user = current_user
		if @submissio.user == nil
		  redirect_to root_path
		  flash[:notice] = "Please log in to create a new submissio"
		elsif
		  @submissio.save
		  params[:submissio][:questions]
		  redirect_to submissio_path(@submissio)
		  flash[:notice] = "Submissio for #{@submissio.authority} has been created"
		else
		  render :new
		end
	end

	def edit
  end

	def update
		params[:answers].each do |k, v|
		  answer = Answer.find(k)
		  answer.content = v
		  answer.submissio = @submissio
		  respond_to do | format |
			  if answer.save
			  	format.html
			  	format.json { render :show, status: :ok, location: @submissio }
			  end
			end
			end
		redirect_to submissio_path(@submissio)
		flash[:notice] = "Submissio for #{@submissio.authority} has been updated"
		# if @submissio.update(submissio_params)
		# 	redirect_to submissio_path(@submissio)
		# 	flash[:notice] = "Submissio for #{@submissio.authority} has been updated"
		# else
		# 	render :edit
		# end
	end

	private

	def set_submissio
	  @submissio = Submissio.find(params[:id])
	end

  def submissio_params
    params.require(:submissio).permit(:authority)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/answers/index.html.erb
<script type="text/javascript">         
  function reloadPage() {
  // The last "domLoading" Time //
  var currentDocumentTimestamp =
  new Date(performance.timing.domLoading).getTime();
  // Current Time //
  var now = Date.now();
  // Ten Seconds //
  var tenSec = 0.1 * 1000;
  // Plus Ten Seconds //
  var plusTenSec = currentDocumentTimestamp + tenSec;
  if (now > plusTenSec) {
  location.reload();
  } else {}
  }
  reloadPage();
</script>

<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1 main-card ansers-form">

    	<%= render 'shared/timeline' %>

			<%= form_for @submissio do | f |  %>
				<% Section.all.each_with_index do | section, index | %>
					<div id="sectionsDiv" data-sectionlength="<%= Section.all.length %>">
						<div class="sub-form form-step" <%= 'hidden' if index > 0 %> id="step-<%= index + 1 %>">
							<h1><%= section.name %></h1>
							<hr/>
							<p> <%= section.description %></p>
							<br>
							<div class="form-input-width-80">
			          <hr/>
			          <% section.questions.each do | question | %>
			          	<div class="input-wrapper">
			          		<div class="question-content">
			          		  <%= question.content %>
			          		</div>
			          		<!-- Checking if there is a question -->
			          		<% answer = @submissio.answers.find_by(question: question) || Answer.create(question: question, submissio: @submissio) %>
			          		<div class="question-content">
			          			<% if question.data_type == "yes or no" %>
			          				<select name="answers[<%= answer.id %>]" style="width:100%" type="<%= question.data_type %>" value="<%= answer.content %>" name="answers[<%= answer.id %>]" class= " input ">
			        					  <option value="yes">yes</option>
			        					  <option value="no">no</option>
			        					</select>
			        				<% else %>
			        					<input style="width:100%" type="<%= question.data_type %>" value="<%= answer.content %>" name="answers[<%= answer.id %>]" id="<%= 'submissio_address' if question.data_type.include?("address") %>" class= "<%= 'datepicker' if question.data_type.include?("date") %> <%= 'datepicker-time' if question.data_type.include?("datetime-local") %> input <%= 'dropdown' if question.data_type.include?("yes or no") %>">
			          			<% end %>
			          		</div>
			          	</div>
			          <% end %>
			        </div>
			      </div>
			    </div>  
				<% end %>
				<br>
			  <%= f.button :"Submit Submissio", id:"submit", class:"btn btn-primary submit submit"  %>
			<% end %>	
			<br>
			<button class="btn btn-secondary" id="previous">Previous</button>
			<button class="btn btn-secondary" id="next">Next</button>

		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Submissio2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <div class="background-main">
      <%= yield %>
    </div>

    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

<%= link_to 'Submissios', submissios_path, class: "btn btn-primary"  %>
<%= link_to 'Sections & Questions', sections_path, class: "btn btn-primary"  %>

app/views/questions/index.html.erb
<h1>Submission der Beschaffungsstelle <%= @submissio.authority %></h1>
<p>Erstellt am: <%= @submissio.created_at %></p>


<% @sections.each do | section |%>
	
	<h3><%= section.name %></h3>		
		<ul>
			<% @questions.where(section_id: section.id).each do | question |%>
				<li class="mb-1">
					Question: <%= question.content %><br>
					<% if question.answers.any? %>
						Answer: <%= question.answers.first.content %>
					<% else %>
						Answer: n/a
					<% end %>
				</li>
			<% end %>
		</ul>

<% end %>

app/views/questions/show.html.erb
<%= @submissio %>

<div class="question-card">
	<div class="question-container">
		
		<%= @question.content %>


	</div>
</div>





<%# Service.all.each do |service| %>
  <!-- <h1><%#= service.name %></h1> -->
  <!-- <ul> -->
  <%# service.service_items.each do |item| %>
    <!-- <li> -->
      <%#= @order.order_items.find_by(service_item: item).content %>
      <%#= @order.order_items.find_by(service_item: item).unit_price %>
    <!-- </li> -->
  <%# end %>
  <!-- </ul> -->
<%# end %>

app/views/sections/index.html.erb
<div class="main-card">
	<h1>Sections</h1>

	<div class="grid-container">
		
		<% @sections.each do | section | %>
		<% add = 0 %>
			
			<div class="section-area">
			
				<h4>id: <%= section.id %>  -  <%= section.name %></h4>
				
				<div class="sections-table">
					<div class="id-section strong">
						id
					</div>
					<div class="id-name-section strong">
						id_name
					</div>
					<div class="content-section strong">
						content
					</div>
					
					<% section.questions.each do | question | %>
						<div class="id-section">
							<%= question.id %>
						</div>
						<div class="id-name-section">
							<%= question.id_name %>
						</div>
						<div class="content-section">
							<%= question.content %>
						</div>
					<% end %>
				</div>

			</div>
		
		<% end %>

	</div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at submissi.o.
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "submissio_logo.png", style: "height:42px;width:auto;" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "default-avatar.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_timeline.html.erb
<ul class="timeline-container">
  <div class="step-progress-bar">
   <!--  <li class="timeline-number"> 1 </li> -->
    <% step = 1 %>
    <% Section.all.each_with_index do | section, index | %>
      <li data-sectionlength="<%= Section.all.length %>" class="<%= 'active' if step == 1 %> sectionTitle timeline-number" id="tile-<%= step %>"> <%= step %> <%#= service.name%>
      </li>
      <% step += 1 %>
    <% end %>
  </div>
</ul>

app/views/submissios/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-10 col-sm-offset-3 main-card">
      <h1>Edit submissio</h1>

      <%= simple_form_for [@submissio] do |f| %>
      
        <div class="form-inputs">
        	<div class="form-group">
          	<%= f.input :authority %>
          </div>
          <%= f.button :submit, "Update Submissio", class: "btn btn-primary" %>
        </div>
      </div>
      
      <% end %>
    </div>
  </div>
</div>

app/views/submissios/index.html.erb
<!-- <p id="notice"><%#= notice %></p> -->

<div class="main-card">
  <h1>Submissios</h1>

  <table class="table">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">User</th>
        <th scope="col">Vergabestelle</th>
        <th scope="col"></th>
        <th scope="col"></th>
        <th scope="col"></th>
      </tr>
    </thead>

    <tbody>
      <% @submissios.each do |submissio| %>
        <tr>
          <td><%= submissio.id %></td>
          <td><%= submissio.user.email %></td>
          <td><%= submissio.authority %></td>
          <td><%= link_to 'Show', submissio %></td>
          <td><%= link_to 'Edit', edit_submissio_path(submissio) %></td>
          <td><%= link_to 'Destroy', submissio, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Submissio', new_submissio_path, class: "btn btn-primary" %>
</div>

app/views/submissios/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-12 col-sm-10 col-sm-offset-1 main-card">

			<%= simple_form_for @submissio do | f | %>
				<h1>Neue submissi.o. erstellen</h1>
				<div class="form-group">
					<%= f.input :authority, label: 'Vergabestelle', error: 'Vergabestelle muss angegeben werden' %>
				</div>
				<%= f.button :submit, "Create Submissio", class: "btn btn-primary" %>

			<% end %>

		</div>
	</div>
</div>

app/views/submissios/show.html.erb
<div class="main-card">

	<h1>Deine submissi.o.</h1>
	<p>Für die Vergabestelle <%= @submissio.authority %></p>
	<p>Erstellt am <%= @submissio.created_at %></p>
	<p>Referenznummer: <%= @submissio.id %></p>

	<div class="submissio-overview">
		
		<% Section.all.each do | section | %>
			<div class="section-card section-card-user">
				<h4 class="card-body"><%= section.name %></h4>
			</div>
		<% end %>

	</div>
	<br>

	<%= link_to "Bearbeiten", submissio_answers_path(@submissio), class: "btn btn-primary" %>
	<br><br>

	<!-- <%#= link_to 'Edit', edit_submissio_path(@submissio) %> | -->
	<%= link_to 'Zurück', submissios_path, class: "btn btn-secondary" %>

</div>